//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMedsMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacySubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PharmacySubCategory()
        {
            this.PharmacyProducts = new HashSet<PharmacyProduct>();
        }
    
        public int PharmacySubCatId { get; set; }
        public string PharmacySubCatName { get; set; }
        public int PharmacyCategoryId { get; set; }
        public byte[] PharmacySubCatImage { get; set; }
    
        public virtual PharmacyCategory PharmacyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyProduct> PharmacyProducts { get; set; }
    }
}
