//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMedsMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public decimal Product_Price { get; set; }
        public byte[] Product_Image { get; set; }
        public string Product_Details { get; set; }
        public int SubClassificationId { get; set; }
    
        public virtual SubClassification SubClassification { get; set; }
    }
}
